### ISSUE TITLE
Slime blocks can move reinforced blocks.

### ISSUE THREAD

**Issue by YoshiSama** [Civcraft/Citadel#101]
Slime blocks attached to pistons can move other blocks reinforced or not.

You can also move a non reinforced block into a reinforced block which carries the reinforcement over as well as just moving the reinforced block out of a reinforcement with the slime block.

All 1.8 unmovable blocks aren't affected (Jukeboxes, chests, obsidian, dispensers, etc)

**Comment by ttk2** [comment]
oh, someone must have tested it with a chest on Civtest, dammit.

**Comment by BlackXnt** [comment]
I think I know how to fix that. Give me a few minutes to make a pull.

**Comment by ttk2** [comment]
thanks, this will go online as soon as its tested due to its severity.

**Comment by BlackXnt** [comment]
https://github.com/Civcraft/Citadel/pull/102#issuecomment-105023185

**Comment by WildWeazel** [comment]
lets wait til this is live

**Comment by rourke750** [comment]
This good to close?

**Comment by BlackXnt** [comment]
yes
