### ISSUE TITLE
Acid blocks usuable by members of same group?

### ISSUE THREAD

**Issue by drjawa** [Civcraft/Citadel#108]

**Comment by ttk2** [comment]
I think that's how its supposed to work?

**Comment by drjawa** [comment]
Members don't have blocks perm so I would think that they'd need at
least that perm to use acid blocks on the same group since it
accomplishes the same thing.

**Comment by jjj5311** [comment]
I think it is working correctly, players need to have the BLOCKS permission to modify reinforcements 

https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/reinforcement/PlayerReinforcement.java#L67

**Comment by drjawa** [comment]
The player who discovered this received the message that they do not have the permission to use the acid block, but the acid block popped anyway.

**Comment by adzjwarner** [comment]
Hi, Yeah that was me... But also, I think I've found the problem:

https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/command/commands/Acid.java#L69

    1. Player has permission:
          -Continue
          -break block (providing all other requirements met)

    2. Player does not have permission:
          -Display message "you do not have sufficient... blah blah"
          -SHOULD RETURN HERE BUT:
          -Fall out of if loop
          -Break block (providing all other requirements met)


You're missing a return :)

**Comment by jjj5311** [comment]
Good catch

**Comment by drjawa** [comment]
Sounds like a quick fix. Any volunteers?

**Comment by drjawa** [comment]
Woops, didn't mean to close issue. 

I've staged it on civtest. I'll restart civtest in a bit once current testers are off.

**Comment by drjawa** [comment]
Huh, got a bunch of Unknown dependency CivModCore and other stuff when I put this on. Probably due to other changes?

@rourke750

**Comment by ttk2** [comment]
Yup other changes. Just toss it on Civtest juenkins has core builds.

**Comment by drjawa** [comment]
Even though it is saying it couldn't load dependencies?

Just checking to be sure

**Comment by rourke750** [comment]
No you need to add CivModCore as well.

**Comment by drjawa** [comment]
Done seems to work. Only bergecore complained.

**Comment by ttk2** [comment]
they might have to live in harmony someday, but it should probably be removed for today.

**Comment by jjj5311** [comment]
@drjawa  did you ever get confirmation that this is solved?

**Comment by drjawa** [comment]
Yeah, the fix is live so this shall be closed.
