### ISSUE TITLE
Crop reinforcement

### ISSUE THREAD

**Issue by erocs** [Civcraft/Citadel#110]
How is crop reinforcement supported in Citadel3? Back with Citadel2 crops, other then pumpkins and melons which were special, weren't directly reinforceable and instead took on the reinforcement of their underlying soil block.

https://www.reddit.com/r/Civcraft/comments/3dnr5t/serious_reinforced_sugarcanes/

**Comment by jjj5311** [comment]
It is handled the same way in citadel3 (that is current right?) 

Crops should be taking their soil block reinforcement. 

https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/Utility.java#L597

I know we are missing a check to make sure its the block right under the last crop... examples would be 

sugarcane block
sugarcane block
dirt (no reinforcement)
dirt (reinforcement) (would act on the 2 sugar cane blocks above

I am not sure why user was getting kicked as they should have been able to break the block reinforcement..

Here is the event taking care of this calling the soil logic stuff
https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/listener/BlockListener.java#L132
