### ISSUE TITLE
Can you just tell me how to install this?

### ISSUE THREAD

**Issue by Omuck3** [Civcraft/Citadel#115]
I have wanted this plugin on my server since February.  (in addition to prisonpearl, jukealert).  I know it needs namelayer, but I just am never able to get it installed.  Can I get some help?  I'm about the try again. D:

**Comment by ProgrammerDan** [comment]
Pm me on reddit, also look at the procedure i outline in my civcraft-vm project. 

Remember you must install civmodcore and namelayer before citadel.

**Comment by Omuck3** [comment]
civmodcore?!??!?!?!!  NO ONE HAS EVER TOLD ME ABOUT IT! :O

**Comment by Omuck3** [comment]
Are there any versions for 1.7?

**Comment by ProgrammerDan** [comment]
It's relatively new, probably introduced since the last time you tried.

In general though, if help has been sparing, it's because the principle developers have very little time to help folks with installations. It's regrettable, but we do encourage that you make every effort to install it on your own first. 

To see what is required to install, check the "pom".

As for 1.7 -- Namelayer and Citadel should be compatible, via the same process as for newer releases of Minecraft.

**Comment by Omuck3** [comment]
Ok.  What's your reddit username?  It's workingbetter now, namelayer can actually do some stuff(like list groups).  Though how do I add groups?  How do I get citadel to work?

**Comment by Omuck3** [comment]
When I tried MySQL manually, it said table faction already exists...

**Comment by ProgrammerDan** [comment]
/u/programmerdan55

All namelayer commands are documented in the wiki, be sure to read there. They are executed client-side; not sure if console versions are enabled or not (haven't tried).

**Comment by Omuck3** [comment]
None of the commands on github are recognized for namelayer. I am using an older version for 1.7.   I have commands like /groupsaccept

**Comment by Omuck3** [comment]
https://copy.com/xunOmn0oYJ4vzYGz

A log from earlier.

**Comment by ProgrammerDan** [comment]
Oh, you can use the latest with 1.7 -- we use NMS techniques so that it is backwards compatible to at least 1.7.2 if not before.

Definitely don't use an old build

**Comment by Omuck3** [comment]
Oh, ok!  Good! :D

**Comment by rourke750** [comment]
You actually wouldn't be able to.

**Comment by Omuck3** [comment]
Wait, what?

**Comment by rourke750** [comment]
Internal library change.

**Comment by Omuck3** [comment]
So what versions of plugins should I use for 1.7.10?

**Comment by ProgrammerDan** [comment]
RIP, here I thought we still had it covered. What's his newest old release, then?

**Comment by Omuck3** [comment]
I used the latest version of citadel from before the upgrade to 1.8

**Comment by rourke750** [comment]
Hey are you still having issues?

**Comment by Omuck3** [comment]
Hi. Thanks for asking.  I am no longer running a server...  Though a few of
the staff members are continuing it
