### ISSUE TITLE
Allow admins to /ctf or /ctr to any group

### ISSUE THREAD

**Issue by rourke750** [Civcraft/Citadel#116]
@Civcraft/devs Can someone here attempt this.  Please comment so I can assign you.

Just go to each Command Class and update I believe the line where it checks if you have permission.  Add an op plus a citadel perm check.  Pretty straight forward.

**Comment by Maxopoly** [comment]
Fixed here: https://github.com/Civcraft/Citadel/commit/d9850f38aaac3383ef30e5c1b5b2523923d6be3d
