### ISSUE TITLE
reinforced half slabs allow placement of another reinforced half slab in the same block place

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Citadel#12]
This results in overwriting the reinforcement of the original half slab, even if the new placement is from a different group or different owner.

**Comment by spaceFountain** [comment]
I think i have a pull request that should fix this.

**Comment by rourke750** [comment]
https://github.com/Civcraft/Citadel/commit/23f9e1847190d75c2d6566283e69a98125b82ccd
