### ISSUE TITLE
Cache repeating comission failure

### ISSUE THREAD

**Issue by psygate** [Civcraft/Citadel#126]
The method referenced @[ReinforcementManager](https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/ReinforcementManager.java#L175) does not schedule [a repeating task](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scheduler/BukkitScheduler.html#runTaskLaterAsynchronously%28org.bukkit.plugin.Plugin,%20java.lang.Runnable,%20long%29), but only a delayed task. This make the cache flush once to the database, and then never again unless issued a manual flush. The probably intended method for this is probably [this one](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scheduler/BukkitScheduler.html#runTaskTimer%28org.bukkit.plugin.Plugin,%20java.lang.Runnable,%20long,%20long%29)

**Comment by rourke750** [comment]
Good catch, I'll fix this.
