### ISSUE TITLE
Inefficient index / database usage

### ISSUE THREAD

**Issue by psygate** [Civcraft/Citadel#127]
Indexes are declared but never used in queries. See [CitadelReinforcementData)[https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/database/CitadelReinforcementData.java]. Either use indexes in queries explicitly, or merge the split up tables.

**Comment by rourke750** [comment]
I don't believe you need to declare index use. From our timing it seems
like indexs work properly.

**Comment by suirad** [comment]
@rourke750 should this remain open then?

**Comment by ProgrammerDan** [comment]
No.
