### ISSUE TITLE
Unnecessary/odd synthetic keys

### ISSUE THREAD

**Issue by psygate** [Civcraft/Citadel#128]
The used database model imposes an unnecessary synthetic key called 'rein_id'. X,Y,Z and World already impose a well defined combined primary key. Given the fact that x,y,z are queried most often, the dm could be reduced to only use x,y,z,world as a primary key. There is no real need to introduce a synthetic key for already well ordered domains. x,y,z,world are all well ordered one dimensional quantities and should be efficiently handled by any modern database.

**Comment by rourke750** [comment]
Removing rein_id would break multiblock reinforcements.
