### ISSUE TITLE
Unbounded(255) varchars

### ISSUE THREAD

**Issue by psygate** [Civcraft/Citadel#131]
"chunk_id varchar(255) not null,"  - A chunk ID cannot be possibly larger than Integer.MAX_VALUE.toString + : + Integer.MAX_VALUE.toString + : + WorldName.max_size which will always be smaller than 255. see https://github.com/Civcraft/Citadel/issues/130 which would also fix this issue
 "world varchar (255) not null," - Same problem as chunk_id. World names are reasonable to assume smaller or equal to 64 characters.

**Comment by ProgrammerDan** [comment]
Since varchar this should have no impact, as the DB _should_ be simply storing the actual size of the variable-length character string, not the full 255 max-allocation block. YMMV depending on database and engine, though ...

In any case I'd prefer to address via #130 vs. this.
