### ISSUE TITLE
Unnecessary synchronization

### ISSUE THREAD

**Issue by psygate** [Civcraft/Citadel#135]
com.google.guava.Cache implementations are expected to be thread-safe per default.
https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/ReinforcementManager.java synchronizes on the cache before access, which is unnecessary. http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/cache/Cache.html

**Comment by ProgrammerDan** [comment]
Appears to have been addressed.
