### ISSUE TITLE
Admins automatically break hardening blocks when they shouldn't.

### ISSUE THREAD

**Issue by ShadedJon** [Civcraft/Citadel#138]
What goes right when an admin places a block without hardening:

>Places block

>Instantly hardens

>Turns off CTB

>Takes one durability off.

---

What happens if the block is still hardening:

>Places block

>Hardens in 15 minutes. Config is set to do double damage while it hardens.

>Turns off CTB

>Breaks at 14.9 minutes into hardening. Breaks at 10 minutes hardening. Breaks at 1 minute hardening.

>General user without op does double damage as normal.

**Comment by rourke750** [comment]
So little confused?  Are you saying that admins only do 1 hit of damage and that the hardening stuff is ignored for admins?

**Comment by rourke750** [comment]
@ShadedJon

**Comment by ProgrammerDan** [comment]
No, Operators/Admins instantly break blocks unless fully hardened.

**Comment by jjj5311** [comment]
Any admin with citadel.admin.bypass bypass will automatically bypass reinforcement it looks like

https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/listener/BlockListener.java#L167

**Comment by ProgrammerDan** [comment]
This is a feature. If you're using pex just do ```pex user add -citadel.admin.bypassmode``` to remove that permission and disable auto-bypass.
