### ISSUE TITLE
pom.xml is faulty

### ISSUE THREAD

**Issue by AkariAkaori** [Civcraft/Citadel#139]
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

No versions are present in the repository for the artifact with a range [1.0.1,)
  vg.civcraft.mc.civmodcore:CivModCore:jar:null

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  civcraft-repo (http://build.civcraft.co:8080/plugin/repository/everything/),
  spigot-repo (https://hub.spigotmc.org/nexus/content/groups/public/)

Path to dependency:
        1) vg.civcraft.mc.citadel:Citadel:jar:3.3.4

**Comment by Maxopoly** [comment]
Just because you cant build it locally by running mvn package doesnt mean it's broken. The dependencies are adjusted to work with our build server and they do that completly fine. If you want the latest Citadel build, you can simply grab it from here: http://build.civcraft.co/job/Citadel-master/
