### ISSUE TITLE
Make sitting on stairs subject to reinforcement permission

### ISSUE THREAD

**Issue by WildWeazel** [Civcraft/Citadel#14]
After looking at the code it may be sufficient to add all of the sit-blocks in Chairs to additionalSecurable in Citadel. I'm not sure if the events will be caught though because both plugins handle PlayerInteractEvent with HIGHEST priority. It seems like Citadel should use a lower priority, maybe NORMAL or even LOW, so that it catches and cancels events earlier before other plugins cause side effects.

**Comment by suirad** [comment]
This could probably be closed. It could be re-opened or remade once chairs integration is actually considered.

**Comment by Maxopoly** [comment]
Agreed
