### ISSUE TITLE
Citadel aggressively flushes the cache if cache size is too small

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/Citadel#141]
Not really a surprise, but the cache size is critical to Citadel performance. New chunk loads in reinforcement heavy areas can effectively clear the cache as they load into it, leading to cache churn as old chunks are loaded, and sharp performance loss on each clear/update interval. 

Quick fix for now is give Minecraft more memory and gratuitously expand the citadel reinforcement cache size.

**Comment by ttk2** [comment]
max_cache_size: 1000000

this is what we have it set to in production, think we should raise it? Also max cache load time is that in seconds or ticks we have it as 1440

**Comment by ProgrammerDan** [comment]
Closing as this is solve-able via configuration tuning.
