### ISSUE TITLE
Creepers blowing up on reinforced crops causes crops to explode

### ISSUE THREAD

**Issue by TealNerd** [Civcraft/Citadel#143]
Not sure if it's an issue with creeper explosions not triggering the explode event, or if the explosion event handling is ignoring crops because it's actually the block under that's reinforced but this is a problemo.

**Comment by ProgrammerDan** [comment]
I can certainly give this a test on civtest, but what do you mean by "explode" ? They are destroyed instantly (citadel bypass)? They do something else funky?

**Comment by jjj5311** [comment]
Is this really a bad thing? Citadel is to protect from other players right

**Comment by ProgrammerDan** [comment]
In terms of bukkit events, Creepers cause the same event as TNT iirc.

**Comment by TealNerd** [comment]
@jjj5311 yeah but since creepers should be triggering the same event as tnt I think it's not the creepers, but rather how we handle the event. Either way it's an issue especially with these new mobs spawning everywhere. The spawning creepers could take out your farms before you can get away from them and I don't think that's an intended effect

**Comment by jjj5311** [comment]
got it, IIRC the issue will be like you said there is not check if it is a crop, should check if its a crop (utility.isPlant)  and then use utility.findplantsoil instead of the getrealblock i think

**Comment by ProgrammerDan** [comment]
Yeah, sounds about right, thanks man!

**Comment by TealNerd** [comment]
#146 :)
