### ISSUE TITLE
Return rein_id when creating a reinforcement

### ISSUE THREAD

**Issue by rourke750** [Civcraft/Citadel#150]
Change insert_rein to a procedure and get the rein_id from the resultset instead of how the system is now.

**Comment by ProgrammerDan** [comment]
Been a while since I made a plug, but  -- reason #9281 to switch to PostGreSQL: INSERT ... RETURNING;  -- http://www.postgresql.org/docs/8.2/static/sql-insert.html

No comparable in Mysql/MariaDB. 

The change you're scoping is best for what we have now though, A+.

**Comment by ttk2** [comment]
Postgre is clearly the future but we don't have the man power to port
everything so soon.
