### ISSUE TITLE
Shard-unaware Citadel

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/Citadel#154]
Citadel is somewhat unique for our plugins; it doesn't care about shards. Currently however it borrows its DB config from Namelayer. While it _does_ need to talk to the Namelayer DB to get database information, it does not need it (or shouldn't) for the majority of simple interactions. 

We should investigate and execute on revamping Citadel and /or Namelayer so that we can effectively decouple them, letting Citadel hit a local DB for its reinforcements instead of all shards hitting a central DB.

**Comment by rourke750** [comment]
Citadel no longer looks at Namelayer for db info
