### ISSUE TITLE
Scale reinforcement material return chance

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/Citadel#165]
An option should be added that allows scaling the chance to return the reinforcement material when bypassing the reinforcement with the relative health of the reinforcement.

For example if a piece of DRO is at half health, you only have 50 % chance to get the diamond back.

**Comment by TealNerd** [comment]
doesn't it already work like this?

**Comment by Maxopoly** [comment]
No, currently it always returns the material with 100 % chance afaik

**Comment by rourke750** [comment]
There's already a configuration option for this.

**Comment by Maxopoly** [comment]
I mentioned it in the dev chat a while ago,  but noone said anything that it already existed

Nvm
