### ISSUE TITLE
Switching a server resets players' reinforcement mode

### ISSUE THREAD

**Issue by BlackXnt** [Civcraft/Citadel#168]

**Comment by suirad** [comment]
I would think this is ideal.

**Comment by suirad** [comment]
Looks like this is completed already 8d9681adc882fbee87c09b75fd7c5e184fbd3f05. 
@ProgrammerDan this issue is older than the above merged pull; it should be closed.

**Comment by Maxopoly** [comment]
I never tested that and one guy said it's not working, should probably test it a bit more

**Comment by Maxopoly** [comment]
I never tested that and one guy said it's not working, should probably test it a bit more

**Comment by Lcth** [comment]
I just tested it on the Bet-Gimmel border and REINFORCEMENT_FORTIFICATION doesn't persist.

**Comment by Maxopoly** [comment]
Alright, thanks for confirming

**Comment by BlackXnt** [comment]
@Maxopoly you didn't register the new listener

**Comment by Maxopoly** [comment]
Okay, I'm officially retarded

**Comment by BlackXnt** [comment]
You have nothing to worry about I am definitely more retarded. It took me 2 hours to understand I need to register the channel in Mercury(you need to add this as well).

**Comment by ttk2** [comment]
so is this issue still open?

**Comment by Maxopoly** [comment]
needs to be tested

**Comment by Maxopoly** [comment]
Alright, awesome. Thanks for testing.
