### ISSUE TITLE
Levers bypass citadel reinforcements

### ISSUE THREAD

**Issue by PatchyKnowly** [Civcraft/Citadel#169]
While pressure plates and torches seem to abide by them, flipping a lever will open doors locked to a group you're not on.

According to bgbba this has been a thing as long as he can remember. If there are plans to add 2d maturation to diamond reinforcements, this is especially significant, as it prevents the use of iron doors as a way to provide access to vaults without breaking the reinforcements.

**Comment by Maxopoly** [comment]
It can bypass them if a member of the group is right next to it

**Comment by PatchyKnowly** [comment]
Oh, I hadn't thought to make bg stand a distance away while testing. Confirmed it just now. 

Was then concerned at how bg was opening doors on the vault when he wasn't on the group and I was offline, but I think we may have figured out how.

bgbba: "no wonder I could get in last time, it started working when maxopoly was standing next to me"
