### ISSUE TITLE
Blocks that water doesn't wash can be washed by directly bucketing them

### ISSUE THREAD

**Issue by PatchyKnowly** [Civcraft/Citadel#170]
If you rightclick a water bucket on rails, redstone, etc. (sometimes you need to hold shift), it will place the water and remove the block, regardless of reinforcement. Have tested with redstone, repeaters, redstone torches, rails, stone buttons and levers.

Of all, only the repeater was immune to direct bucket application (though the waterflow interaction is cool).
![160229-19 46 51](https://cloud.githubusercontent.com/assets/8378762/13406814/669ee9be-df1d-11e5-8968-b046353f21c0.png)

 I think https://github.com/Civcraft/Citadel/pull/86 might vaguely relate to this.

**Comment by ProgrammerDan** [comment]
Oh good catch, I'd received this report without any details once before. Thanks.

**Comment by suirad** [comment]
Could we get a bug tag and priority added?

**Comment by ProgrammerDan** [comment]
You want this one @suirad ?

**Comment by suirad** [comment]
Sure I'll take it.

**Comment by ProgrammerDan** [comment]
once you accept the invite I'll add you.

**Comment by suirad** [comment]
What invite?

**Comment by ProgrammerDan** [comment]
Check the email you have registered to this github account. I invited you as a member of the Members in the Civcraft org.

**Comment by suirad** [comment]
It is done

**Comment by suirad** [comment]
This can be closed.
