### ISSUE TITLE
Repeating percentage after specific intervals

### ISSUE THREAD

**Issue by hypirontriferion** [Civcraft/Citadel#193]
Every so often at specific intervals of breaking reinforcement that is not on the same group the percentage of health for the block displays a repeating number after decimal point. I understand this is probably fairly low on the issue board but thought I might bring it up for later patching.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/Citadel/commit/7bb66080b3a82585718449a5ceb68b9c55df04f4
