### ISSUE TITLE
Planting crops on already reinforced farmland with /ctf further reinforces the crop

### ISSUE THREAD

**Issue by gipsy-king** [Civcraft/Citadel#196]
Steps to reproduce:

1. Reinforce a farmland
2. Enter fortify mode with `/ctf`
3. Plant a crop

Result: one reinforcement is deducted from inventory (which is impossible to recover due to farmland-reinforcement mechanics), the particle effect appears on the crop-block.

Expected result: Nothing citadel-related should happen

**Comment by Maxopoly** [comment]
For all crops? Those should just be included in the list of non reinforceable materials

**Comment by gipsy-king** [comment]
I tried with carrots and beetroot seeds, same result.
Sugarcane gives correct "... not a reinforceable material" chat message and no reinf.

**Comment by Maxopoly** [comment]
That was due to a config error. I added carrots, potatoes, chorus and beetroot. Let me know if you find any other that should be added
