### ISSUE TITLE
Change members to have CROPS permission default?

### ISSUE THREAD

**Issue by drjawa** [Civcraft/Citadel#35]
Any thoughts on this? It'd be more convenient for people and help them transition as they learn namelayer. 

In 2.0, members are able to harvest crops (I think), so this behavior would be consistent without being bad.

**Comment by drjawa** [comment]
Rourke's explained that this won't quite work due to lack of BLOCKS perms

**Comment by rourke750** [comment]
It would work but it makes sense to have both you know.
