### ISSUE TITLE
Proper handling for transferring a group to a logged out player

### ISSUE THREAD

**Issue by spaceFountain** [Civcraft/Citadel#36]
This may be because I'm a admin on my test server but I got an stack trace when I attempted to transfer  a group to a made up user. The goal was to no longer be part of the group so I could test my pull request, but instead it triggered an exception. Can we add proper handling for normal players so they understand what went wrong and someway to test for devs?

**Comment by WildWeazel** [comment]
I was also getting error messages when trying to ;eave/remove myself from my own group, which may be related.

**Comment by spaceFountain** [comment]
Wops don't know why I put this here it should be in NameLayer
