### ISSUE TITLE
Bedrock, flowers, and long grass is reinforceable

### ISSUE THREAD

**Issue by drjawa** [Civcraft/Citadel#39]
https://www.reddit.com/r/CivTesters/comments/2tf1vw/last_chance_citadel_namelayer_30_general_test/cnzblnu

**Comment by ttk2** [comment]
did the config values we have to stop that get broken during the update?

**Comment by drjawa** [comment]
Not sure. Checking the config it seems that these items are still in the 
config as non-reinforceables.

Don't know how reliable that is, because melon stem and pumpkin stems 
are also on that list, but they've been reinforceable for long time.

**Comment by rourke750** [comment]
https://github.com/Civcraft/Citadel/commit/d7d181456a4960a403dad301742ccf11438d2309

**Comment by drjawa** [comment]
Rourke saves the day
