### ISSUE TITLE
switch to inner join

### ISSUE THREAD

**Issue by rourke750** [Civcraft/Citadel#40]
https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/database/CitadelReinforcementData.java#L99

https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/database/CitadelReinforcementData.java#L150

**Comment by ttk2** [comment]
Should I grab a new jar?

**Comment by rourke750** [comment]
No this is an issue for me
