### ISSUE TITLE
Make permissions settable as a flag like chmod does

### ISSUE THREAD

**Issue by AkariAkaori** [Civcraft/Citadel#41]
The 15 perms can be concisely represented with 4 hexadecimal digits that can easily be copy-pasted and memorised instead of multiple cumbersome commands (which are far more prone to human error and user frustration)

For example

|Permission Name|Flag|
|---|-------|
|DOORS|0x0001|
|CHESTS|0x0002|
|BLOCKS|0x0004|
|ADMINS|0x0008|
|MODS|0x0010|
|MEMBERS|0x0020|
|PASSWORD|0x0040|
|SUBGROUP|0x0080|
|PERMS|0x0100|
|DELETE|0x0200|
|JOIN_PASSWORD|0x0400|
|MERGE|0x0800|
|LIST_PERMS|0x1000|
|TRANSFER|0x2000|
|CROPS|0x4000|

So instead of

```
/nlgmp group-name add PlayerType DOORS
/nlgmp group-name add PlayerType CHESTS
/nlgmp group-name add PlayerType CROPS
/nlgmp group-name add PlayerType BLOCKS
/nlgmp group-name add PlayerType MERGE
/nlgmp group-name add PlayerType DELETE
```

You could type

```
/nlgmp group-name flags PlayerType 4A07
```

Or even just set flags command like so

```
/nlgmp group-name flags PlayerType DOORS CHESTS CROPS BLOCKS MERGE DELETE
```

Also ensure that it remove all permissions not specified in the flag set

**Comment by drjawa** [comment]
This should be in https://github.com/Civcraft/NameLayer/
