### ISSUE TITLE
Reinforced pistons extend but never retract

### ISSUE THREAD

**Issue by infinitycyberworks** [Civcraft/Citadel#50]
To reproduce, place a reinforced piston, stone and button so that the piston should extend when the button is pressed and then retract.

Press button.

Observe piston extend and never retract.

This is new behavior and existing designs are effected (is designs that previously worked now Jam as described)

**Comment by ttk2** [comment]
that's how pistons where previously affected what changed I wonder

**Comment by infinitycyberworks** [comment]
Not sure I understand? If you're saying this is the behavior Pryor to upgrade I respectfully suggest you're likely mistaken (several folks are reporting existing designs suddenly breaking)

Please let me know if I can help in any way. Xexorz in game.

**Comment by ttk2** [comment]
its fixed now

**Comment by infinitycyberworks** [comment]
Excellent! Ty Sir
