### ISSUE TITLE
Feature suggestion: reinforce and bypass separate permissions in a group

### ISSUE THREAD

**Issue by GavJenks** [Civcraft/Citadel#57]
From Hantzu's thread

**Comment by rourke750** [comment]
Don't feel like this is necessary.

**Comment by GavJenks** [comment]
I'm not sure it would be widely used, no, but it definitely has uses. For example, you could give it to soldiers to be able to repair holes in a vault or walls or replace broken bastions, etc. (reinforce), without having to trust that soldier not to break into the middle of the vault (bypass) if bribed or something.

**Comment by ttk2** [comment]
interesting, but your goal seems to make a no trust citadel, that's not
somthing I agree with.

**Comment by GavJenks** [comment]
Okay.
