### ISSUE TITLE
Some hoppers not working

### ISSUE THREAD

**Issue by danquist** [Civcraft/Citadel#62]
Some of our hoppers at the carson pumpkin farm are no longer working. There's a collection system of hoppers and chests, they all seem to work except for the very top hoppers. They won't transfer anything into the chest below it. Everything is on the same group.

Coordinates are -6168, 72, -383 if an admin (Jawa) wants to check it out.

**Comment by ttk2** [comment]
hmm what's the group structure like on this whole thing?

**Comment by danquist** [comment]
All the hoppers and chests are on the same group. I've replaced the chest and hoppers a few times, but that doesn't help.

cliffnerd was reporting the same problem at his wheat farm last night.

**Comment by ttk2** [comment]
hmm ok then, Roruke might get temporary superfriend powers soon to help
handle this .

**Comment by jjj5311** [comment]
I have 1 hopper doing this as well

**Comment by ttk2** [comment]
only one? is it any different from the others?

**Comment by jjj5311** [comment]
Nope

It is a stone reinforced hopper feeding an iron reinforced chest

**Comment by jjj5311** [comment]
hmm if i turn the hopper spout in a different direction it works

**Comment by rourke750** [comment]
Fix is on civtest
