### ISSUE TITLE
Piston heads get stuck if they touch a reinforced block

### ISSUE THREAD

**Issue by PatchyKnowly** [Civcraft/Citadel#67]
While reinforced pistons not retracting seems to be fixed, I've discovered a new issue:

If a piston head extends to touch a reinforced block, the head gets stuck extended until the reinforced block is broken. This happens regardless of whether the piston is reinforced. This does not happen if the reinforced block is above, below or to the sides of the extended piston head.

![2015-02-09_09 35 09](https://cloud.githubusercontent.com/assets/8378762/6103737/2daf5bb0-b03f-11e4-8f20-797414a768b8.png) 
Civtest as of 15-02-09 9:35 UTC+0
top dirt block: unreinforced, bottom dirt block: reinforced

**Comment by rourke750** [comment]
Its been like this a while

**Comment by PatchyKnowly** [comment]
Oh, fair enough. I guess I'd somehow not encountered it until now. Didn't notice it in any of the existing/closed issues so I made a new one.

**Comment by spaceFountain** [comment]
Yep. Honestly though it could be fixed so probably worth doing. Biggest problem might be a race condition if the group is modified somehow while the piston is moving.

**Comment by rourke750** [comment]
Should be modified since it's all synchronous.  Anyways we can just add a
check if it is a piston (not a sticky) and it won't pull anything so well
allow it.

**Comment by suirad** [comment]
@ProgrammerDan I may look into this as well.

**Comment by suirad** [comment]
@PatchyKnowly are you still able to reproduce this? i am trying to in my testing env and am having troubleties

**Comment by PatchyKnowly** [comment]
Oh gosh, this was quite a long time ago, before 1.8 even. 

Anyway, I did a test on CivTemp just now and I can't reproduce it, so it seems it got fixed at some point.
