### ISSUE TITLE
Cauldron Issue

### ISSUE THREAD

**Issue by Omuck3** [Civcraft/Citadel#73]
Cauldron Version: 1.7.10-1.1207.01.195

Pastebin: http://pastebin.com/deE7QVWC

**Comment by rourke750** [comment]
Any other data?  What build number is this?

**Comment by Omuck3** [comment]
Hi.  I think it's not making a database.  How do I fix it?

**Comment by rourke750** [comment]
Do you have namelayer?

**Comment by Omuck3** [comment]
Yes

**Comment by rourke750** [comment]
Download latest version see if that fixes anything.

**Comment by Omuck3** [comment]
Here's the issue.  Please help.
http://pastebin.com/Y2K22UWm

**Comment by rourke750** [comment]
What version of everything are you running?

**Comment by Omuck3** [comment]
Citadel: Master 3.2.3-93
NameLayer: 2.3.3-109

**Comment by rourke750** [comment]
update to newest jar.  Make sure you delete the old copies, dont just
overwrite them.

**Comment by Omuck3** [comment]
Newest jar of which?  I've tried both from github.

**Comment by rourke750** [comment]
You are six versions behind here:
http://192.99.169.83:8080/job/Citadel-master/99/

**Comment by Omuck3** [comment]
Oh, thanks!

**Comment by Omuck3** [comment]
Still get an internal server error.

**Comment by jjj5311** [comment]
Stack trace?

**Comment by Omuck3** [comment]
http://pastebin.com/QmbV0qzt

**Comment by Omuck3** [comment]
There's the latest error

**Comment by rourke750** [comment]
Did you configure mysql?

**Comment by Omuck3** [comment]
No, how do I?

**Comment by ttk2** [comment]
if you mean "how do I configure mysql to work with Citadel" that should be
in the documentation, if you mean "how do I configure a mysql server" then
you need google as we don't support programs we don't write.

**Comment by Omuck3** [comment]
Hi. I am attempting to run citadel on my server. If I add my database to namelayer and try /ctr it tells me to set a default group with /nlsdg

By trying /ctr without adding the database info to namelayer, I get this: http://pastebin.com/y6hAHQUZ

PLEASE HELP!!!

**Comment by jjj5311** [comment]
You need to do /ctr <groupname> if you do not have a default group

**Comment by rourke750** [comment]
He doesnt have mysql configured.

**Comment by Omuck3** [comment]
That's the MySQL error.

0	12	18:13:19	CREATE TABLE `personal_group` ( `group_name` varchar(255) NOT NULL, `owner_name` varchar(255) DEFAULT NULL, PRIMARY KEY (`group_name`) )	Error Code: 1050. Table 'personal_group' already exists	0.078 sec



Then I get this in game:
http://pastebin.com/5CqSBhbW

**Comment by rourke750** [comment]
clear all your tables in mysql created via citadel / namelayer/
