### ISSUE TITLE
Reinforced dirt doesn't reinforce associated crops

### ISSUE THREAD

**Issue by erocs** [Civcraft/Citadel#74]
https://www.reddit.com/r/Civcraft/comments/2x3wi1/morning_changelog_20150225/cowmxfm

"This may or may not be the right place...
Under Citadel 2.0, if we reinforced the ground underneath crops, it would cause the crops that grew to be reinforced, too.
This no longer seems to be the case in 3.0 (at least, not on the stuff that was reinforced before the change)
Is this by design?"

**Comment by rourke750** [comment]
prob a bug.

**Comment by jjj5311** [comment]
tested pull #75 locally and it works for the crops i tested

**Comment by erocs** [comment]
How are reinforced crops handled differently in Citadel3 vs 2? Was some data migration needed to support the same type of reinforcement delegation?

**Comment by jjj5311** [comment]
I think i have them being handled the same way, I think i simplified the delegation aspect though. 

I don't think any data is needed since it just checks the crops soil reinforcement...

Question though on if they break the crop 25x should the block below it become unreinforced?

**Comment by erocs** [comment]
> if they break the crop 25x should the block below it become unreinforced?

Yes

**Comment by jjj5311** [comment]
okay, i think this works then

**Comment by adzjwarner** [comment]
Is this supposed to be working on the live server? Because it does not.

**Comment by jjj5311** [comment]
no, this will have to go onto civtest first whenever someone gets time to
build and reload the server... then after testing it will go to live server
as long as there are no issues

**Comment by erocs** [comment]
We'll need to stage http://192.99.169.83:8080/job/Citadel-master/94/.

**Comment by Promofaux** [comment]
OK, will keep an eye and see if I can test on civtest tomorrow/whenever it's up

**Comment by ttk2** [comment]
on civtest

**Comment by erocs** [comment]
Could we get the debug logging removed if this works?

**Comment by jjj5311** [comment]
Yes I thought I removed it all but I missed two lines

**Comment by ttk2** [comment]
so we need another pull request to get that removed?

**Comment by jjj5311** [comment]
Yes... Or someone could just remove with GitHub editor

**Comment by ttk2** [comment]
its on Civtest, has it changed enderman spawning there?

**Comment by jjj5311** [comment]
Wrong thread

**Comment by ttk2** [comment]
oh, whooops, anyways could someone get the extra lines removed?

**Comment by jjj5311** [comment]
they are removed in pull #76

**Comment by ttk2** [comment]
on civtest for final testing

**Comment by ttk2** [comment]
this is going into production, close the issue if we receive no problem reports after that.

**Comment by ttk2** [comment]
I think we can close this now.
