### ISSUE TITLE
Please make paintings and item frames reinforce-able (I mean if signs can be...) 

### ISSUE THREAD

**Issue by CodingMonkeyXYZ** [Civcraft/Citadel#82]
Seems a little silly to not be able to reinforce paintings and item frames if we can reinforce things like sign posts. 

At the moment these are hands-down the most fragile and unprotected blocks. You can shoot them with an arrow from 50 meters away and they smash instantly.

I'm not against people being able to break these but let's at least make it harder work for them to do so please?

**Comment by rourke750** [comment]
paintings and item frames are entities which is the reason why they can't be reinforced.  Also reinforcing them wouldn't serve much merit as you can insta break all of these entities.

**Comment by WildWeazel** [comment]
Yeah I'm not sure this is technically feasible, unfortunately. Would be nice if it is.

**Comment by erocs** [comment]
I looked at this over a year ago and it was a lot of work to make work right.

**Comment by erocs** [comment]
Why close this? It's still valid even if it may never get done.

**Comment by suirad** [comment]
This can be assigned to me. I have most of this finished and working. All that is left is making cti work on them and locking item frames to the reinforcement group. Expect a pull soon. I may also include armour stands as well. I cant remember, are there any other static entities that could be beneficial to reinforce? 

Also i did think about adding a config option called 'entity_reinforcement_multiplyer' which would mutiply the default reinforcement values and be toggable. 
@ttk2

**Comment by suirad** [comment]
@Maxopoly please assign to me, it is what I am working on currently.

**Comment by ProgrammerDan** [comment]
woops, meant to do that yesterday.

**Comment by suirad** [comment]
You think I should add that entity reinforcement multiplier config option? Most entities break on click/interaction, and most reinforcement values aren't really unreachable within 5min or so.

**Comment by WildWeazel** [comment]
What if they only break with an axe/pick, and take durability?

**Comment by suirad** [comment]
While a step in the right direction, it would only serve as a redirection to the same quick break. I believe the ideal direction would be a way to scale the time-to-break of reinforced entities to match the time of blocks of equivalent reinforcement materials. Then it could be justified to spend the resources to reinforce the item in the first place.

**Comment by erocs** [comment]
Citadel2 had reinforcement scaling. I don't know if it carried forward to
v3.

**Comment by suirad** [comment]
I am not familiar.

**Comment by ttk2** [comment]
the goal of reinforcement scaling is that all objects reinforced with a given resource type (lets say diamond) take the same amount of time to break, so diamond reinforced dirt would take more breaks but the same total amount of time as diamond reinforced obsidian.

**Comment by suirad** [comment]
How would the different break speeds per tool and different enchants, apply to the scaling?

**Comment by ttk2** [comment]
enchants would still speed up the process, as would the right tool, the scaling is simple done with a baseline tool (aka if a vanilla pick takes x time to break B block then we need N breaks to get the R reinforcement material target break time)

**Comment by suirad** [comment]
Ah okay I understand. I am not sure if it is in the current citadel, or I haven't seen anything for it. Perhaps that escapes the scope of this issue though. Is there any additional features/configuration/info you want added for entity reinforcement?

**Comment by rourke750** [comment]
I believe the best thing to do would just add more durability so that it
takes the same amount of time to break.

**Comment by WildWeazel** [comment]
What's the point of scaling block materials? Doesn't that defeat the whole purpose of obsidian, if you can make a vault out of dirt that's just as durable?

**Comment by ProgrammerDan** [comment]
I don't see the point of scaling either. 

Just having frames and paintings not instant-break is sufficient.

**Comment by erocs** [comment]
When we tested scaling 2 or 3 years ago we decided not to use it.

**Comment by suirad** [comment]
Good to close.
