### ISSUE TITLE
Sand losing its reinforcement

### ISSUE THREAD

**Issue by kwizzlehazzizle** [Civcraft/Citadel#83]
Hello!
There is a bug with reinforced sand losing its reinforcement and then falling down.

Basically, I'll place the sand floating in the sky and it will stay and when I come back to it later on (when I finish placing the sand and am placing the cactus it will fall down. The sand that falls down seems to also pull down the sand that was underneath it, but only sometimes

so if this is the before:
S = sand
A = air
G = ground

SSSSSSSS
AAAAAAAA
SSSSSSSS
AAAAAAAA
GGGGGGG

Then this is the after
AAAAAAAA
AAAAAAAA
SSSSSSSS
SSSSSSSS
GGGGGGG

I've encountered this maybe a dozen time while building this cactus farm , all times the tick was around 12-13 tps so I don't know if this is due to lag or not, but whenever I'm online that is what the tps is.  This happened both yesterday and today.  (march 23rd 2015)
http://imgur.com/pwkWRRH

**Comment by rourke750** [comment]
This may be a spigot issue.  That would not be fun :/.  I bring this up because the code is practically identical to what the code was in 2.0

**Comment by TealNerd** [comment]
close this?
