### ISSUE TITLE
Provide group id in admin version of /cti

### ISSUE THREAD

**Issue by erocs** [Civcraft/Citadel#89]
Today the admin version of /cti shows the group name, but with NameLayer groups this could map to any number of group IDs. Please add the group number to the information.

**Comment by erocs** [comment]
That pull doesn't fix this.

**Comment by rourke750** [comment]
https://github.com/Civcraft/Citadel/commit/d75674c365a2a0569c9856c0ca04f55592d938da https://github.com/Civcraft/Citadel/commit/0ca115e3894224c3a8357d60cd2db01bae23ad30#diff-35250cb092462f1ea9f47e16d8a7d5d5

**Comment by erocs** [comment]
Instead of displaying the group ID, this displays the internal string representation of the PlayerReinforcement object.

**Comment by rourke750** [comment]
Already fixed in newest version.
