### ISSUE TITLE
Cactus Over Time Will Break citadel reinforced blocks.

### ISSUE THREAD

**Issue by vicccyy** [Civcraft/Citadel#91]
Not sure if this is a bug or is intentional but when a cactus grows it will break the reinforcement above it until the block eventually has no reinforcement left. I,e sand above cactus will eventually fall as the reinforcement breaks over time.

**Comment by WildWeazel** [comment]
Can you provide a screenshot? I'm not sure I follow what's happening.

**Comment by vicccyy** [comment]
Not really essentially when cactus grows below a block it will damage the
reinforcement.

**Comment by WildWeazel** [comment]
So after a cactus block spawns at x, y, z it will damage the reinforcement at x, y+1, z? What do you mean by "eventually" and "over time"?

**Comment by jjj5311** [comment]
any update on this?

**Comment by ttk2** [comment]
@vicccyy would have to update us

**Comment by gipsy-king** [comment]
Behaviour has changed since cactus are persistent. Cactus growth is now controlled through RB persistence, vanilla growth is always prevented and RB only puts a new cactus block in air blocks.

**Comment by ttk2** [comment]
so can we close this for the time being?

**Comment by gipsy-king** [comment]
yea
