### ISSUE TITLE
Speedup cached chunk unloading 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Citadel#98]
Right now Citadel spends a significant amount of DB time dumping its cache on shutdown, from what I understand it saves out cache day to the DB throughout the day anyways, meaning that whatever data that is in the cache that has not been modified since it was last saved out does not need to be sent to the DB on shutdown. 

It would be nice to see shutdown speed up by adding 'dirty' var to the cache storage for each entry that is false until the data is modified then set back to false when its unloaded, then you can lazy unload chunks on shutdown with no loss of consistency. 

This is a wishlist feature, but it would be nice.

**Comment by rourke750** [comment]
https://github.com/Civcraft/Citadel/commit/0f3ecf8bab2bf386e4a67d7be2eed7a049584e99

**Comment by ttk2** [comment]
this will need to be tested pretty decently. thanks though.

**Comment by rourke750** [comment]
It really wasn't too many lines.  A code review would be better than s test
to make sure I didn't miss anything.
